[db4s]
server = "docker-dev.dbhub.io"
port = 9445
certificate = "/dbhub.io/docker/certs/docker-dev.dbhub.io.cert.pem"
certificate_key = "/dbhub.io/docker/certs/docker-dev.dbhub.io.key.pem"
ca_chain = "/dbhub.io/docker/certs/ca-chain-docker.cert.pem"

[diskcache]
directory = "/home/dbhub/.dbhub/disk_cache"

[environment]
environment = "test"
user_override = "default"

[event]
delay = 2
email_queue_processing_delay = 5
smtp2go_key = ""

[licence]
licence_dir = "/dbhub.io/default_licences"

[memcache]
default_cache_time = 2592000
server = "localhost:11211"
view_count_flush_delay = 120

[minio]
server = "localhost:9000"
access_key = "minio"
secret = "minio123"
https = false

[pg]
database = "dbhub"
num_connections = 45
port = 5432
server = "localhost"
ssl = false
username = "dbhub"

[sign]
cert_days_valid = 365
intermediate_cert = "/dbhub.io/docker/certs/intermediate-docker.cert.pem"
intermediate_key = "/dbhub.io/docker/certs/intermediate-docker.key.pem"

[web]
base_dir = "/dbhub.io"
bind_address = ":9443"
server_name = "docker-dev.dbhub.io:9443"
certificate = "/dbhub.io/docker/certs/docker-dev.dbhub.io.cert.pem"
certificate_key = "/dbhub.io/docker/certs/docker-dev.dbhub.io.key.pem"
request_log = "/var/log/dbhub/request.log"
session_store_password = "example"

[api]
base_dir = "/dbhub.io"
bind_address = ":9444"
server_name = "docker-dev.dbhub.io:9444"
certificate = "/dbhub.io/docker/certs/docker-dev.dbhub.io.cert.pem"
certificate_key = "/dbhub.io/docker/certs/docker-dev.dbhub.io.key.pem"
request_log = "/var/log/dbhub/api_request.log"
session_store_password = "example2"
website_name = "DBHub.io"
